debug: false
spring:
  ai:
    azure:
      openai:
        api-key:
        endpoint: https://springai.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-4o
        embedding:
          options:
            deployment-name: text-embedding-ada-002
    vectorstore:
      azure:
        api-key: 
        url: https://springaisearch.search.windows.net
        index-name: carina_index